### PR TITLE
Update Q53

### PR DESCRIPTION
**Pull request by albheim**
This is more what was done in the python solution. It creates an integer array (not just having integer values, but also integer types) in the same place as the float array, and puts the truncated values from the original array there. 

Suggested python solution from https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md
```python
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)
```

Not sure when I would do this, but thought I would put it here in case you wanted it.

### CODE REVIEW

**Comment by RoyiAvital** [comment]
When I think about it, wouldn't the right solution (As written not in Python) be something like:

1. Generate the `Float32` array.
2. Interpret the array as `Int32`.
3. Per element, interpret as `Float32` (Get back the original value) and round it to `Int32` and save back.

In the above we never allocate more memory, right?

**Comment by albheim** [comment]
My view of the python is that 
* Generate Float32 array
* Create a new view of the array which interprets the memory there as int32
* Overwrite the view elementwise with the trucated integer value of the original float.
so it doesn't allocate anything, but I'm no expert so might be wrong there.

That was at least the behaviour I was trying to recreate.

**Comment by albheim** [comment]
Okay, just saw what you maybe were talking about. My solution was wrong, both wrote VB instead of vB and forgot the .= in the last assignment... 

Didn't look at the code I actually submitted when I answered you first, just looked at the one I had run locally. And the copy was clumsy...

**Comment by albheim** [comment]
And it seems the last line actually allocates a little, seems to be from the trunc function when run on an array, not sure why that happens.

**Comment by RoyiAvital** [comment]
Have no worries. On the code I pushed I used `@.` and fixes `vB`.

**Pull request merged**
